baseURL: "https://vishalchovatiya.github.io/"
title: 'Vishal Chovatiya'
paginate: 50
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#search-not-working-
outputs: # For search page search.md
  home:
    - HTML
    - RSS
    - JSON # necessary for search
searchHidden: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Vishal Chovatiya
  description: "Vishal Chovatiya's personal website"
  keywords: [Blog, Portfolio, PaperMod]
  author: 'Vishal Chovatiya'
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/trident_favicon.webp"
    favicon16x16: "/images/trident_favicon.webp"
    favicon32x32: "/images/trident_favicon.webp"
    apple_touch_icon: "/images/trident_favicon.webp"
    safari_pinned_tab: "/images/trident_favicon.webp"

  label:
    text: "Vishal Chovatiya"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Vishal Chovatiya
    subtitle: "Geek🤓Hipster👓Fitness Freak💪Always a Student🧑‍🎓Productivity Hacker⌚"
    imageUrl: "images/DP.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: DP
    buttons:
      - name: About Me
        url: /pages/vishal-chovatiya
      - name: Latest
        url: posts
      # - name: Categories
        # url: categories
      - name: Search
        url: /pages/search

  # home-info mode
  homeInfoParams:
    Title: "Hi There...! \U0001F44B"
    Content: "I am Vishal"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/vishal-chovatiya/"
    - name: github
      url: "https://github.com/vishalchovatiya"
    - name: x
      url: "https://twitter.com/_V_shal"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    # responsiveImages: true
    # linkFullImages: true
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: https://github.com/vishalchovatiya/blog/blob/main/vishalchovatiya/content
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: 
      name: "About Me"
      weight: 10
      url: "/pages/vishal-chovatiya"
    - identifier: 
      name: "Start Here"
      weight: 20
      url: "/pages/start-here"
    - identifier: latest
      name: Latest
      url: /posts/
      weight: 30
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 40


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
PygmentsCodeFences: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: 'github' # isnt working
