baseURL = 'https://vishalchovatiya.github.io/'
languageCode = 'en-us'
title = 'Vishal Chovatiya'
theme = "hugo-coder"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true


[params]
author = "Vishal Chovatiya"
description = "Vishal Chovatiya's personal website"
keywords = "blog,developer,personal"
info = ["Geek", "Hipster", "Blogger", "Fitness Freak", "Always a Student", "Productivity Hacker"]
avatarURL = "images/DP.jpg"
math = true
dateFormat = "January 2, 2006"
maxSeeAlsoItems = 5 # Series see also post count
hideColorSchemeToggle = true
commit = "https://github.com/vishalchovatiya/vishalchovatiya.github.io" # Git Commit in Footer, uncomment the line below to enable it

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/vishalchovatiya"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/_V_shal"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/vishal-chovatiya/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
# languageName = ":uk:"

[[languages.en.menu.main]]
name = "About Me"
weight = 1
url = "posts/about"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"


# Theme config options: https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md
# exampleSite: https://github.com/luizdepra/hugo-coder/tree/main/exampleSite